[package]
name = "rs2048"
version = "0.1.0"
authors = ["sandb"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.20.3"
rand = "0.7"
chrono = "0.4.11"
